name: stok_anandam
description: "A new Flutter project."
publish_to: 'none'

version: 1.1.19+20

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.3.0
  built_value: ^8.6.0
  built_collection: ^5.1.1
  get_it: 9.2.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  go_router: ^14.2.0
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.10+1
  flutter_img: ^0.2.1+159
  path_provider: ^2.1.3
  my_api_client:
    path: ./lib/data/api_client
  open_filex: ^4.5.0
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  camera: ^0.11.0
  camera_windows: ^0.2.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.11
  printing: ^5.14.3
  pdf: ^3.11.3
  url_launcher: ^6.3.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  intl: ^0.19.0
  google_fonts: ^8.1.0
  pluto_grid: ^8.0.0
  flutter_secure_storage: ^10.0.0
  stomp_dart_client: ^3.0.1
  flutter_typeahead: ^5.2.0
  package_info_plus: ^8.0.0
  ota_update: 7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^3.10.1
  flutter_lints: ^4.0.0
  build_runner: ^2.4.0
  built_value_generator: ^8.6.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/Movva by Anandam.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/icon-anandam.svg
    - assets/images/anandam-logo.svg
    - assets/images/anandamid-logo.svg
    - assets/images/

msix_config:
  display_name: Movva by Anandam
  publisher_display_name: Anandam.id
  identity_name: com.example.stokanandam
  publisher: CN=Anandam, O=Anandam, L=Indonesia, S=DIY, C=ID
  msix_version: 1.1.19.20
  logo_path: assets/images/Movva by Anandam.png
  capabilities: internetClient, location, camera
  install_certificate: false
  install_path: https://stok.anandam.id/app-storage/stok_anandam.msix
